sudo: false
language: ruby
cache: bundler
rvm:
- 2.6.3
before_install: gem install bundler -v 2.0.2
deploy:
  provider: rubygems
  api_key: $API_KEY
  gem: silicium
  on:
    tags: true
    repo: mmcs-ruby/silicium
